INSERT INTO uniquesets(uni_que_pk, title) values(1, 'Amazon EC2');
INSERT INTO uniquesets(uni_que_pk, title) values(2, 'ABCD');




insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(1, 1, 'Which statement describes the Amazon EC2 service?', 'It provides containers to run applications on AWS.', 'It provides virtual machines that run on AWS.', 'It is a serverless compute service.', 'It is a solution that gives customers the ability to deploy their application to run on AWS.', 2, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(2, 1, 'A developer wants to run an application that loads a large amount of data into memory on an Amazon EC2 instance. Which instance type should the developer choose to achieve the best performance?', 'General purpose','Accelerated computing','Memory optimized', 'Compute optimized', 3, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(3, 1, 'Which of the following actions preserves the data on an Amazon EC2 instance that uses an instance store as root volume?', 'Reboot', 'Stop', 'Terminate', 'Hibernate', 1, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(4, 1, 'Which of the following statements are true about security groups for Amazon EC2 instances?', 'They support adding rules that deny traffic from specified sources.', 'They support adding rules that allow traffic from specified sources.','They allow all inbound traffic by default.','They allow all outbound traffic by default.', 2, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(5, 1, 'A company needs to run an application that is fault tolerant and tolerates interruptions on AWS. Which pricing model would best fit their requirements and help them lower costs as much as possible?', 'On-Demand Instances', 'Reserved Instances', 'Dedicated Instances', 'Dedicated Instances', 4, -1);


insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(6, 2, 'Which statement describes the Amazon EC2 service?', 'It provides containers to run applications on AWS.', 'It provides virtual machines that run on AWS.', 'It is a serverless compute service.', 'It is a solution that gives customers the ability to deploy their application to run on AWS.', 2, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(7, 2, 'A developer wants to run an application that loads a large amount of data into memory on an Amazon EC2 instance. Which instance type should the developer choose to achieve the best performance?', 'General purpose','Accelerated computing','Memory optimized', 'Compute optimized', 3, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(8, 2, 'Which of the following actions preserves the data on an Amazon EC2 instance that uses an instance store as root volume?', 'Reboot', 'Stop', 'Terminate', 'Hibernate', 1, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(9, 2, 'Which of the following statements are true about security groups for Amazon EC2 instances?', 'They support adding rules that deny traffic from specified sources.', 'They support adding rules that allow traffic from specified sources.','They allow all inbound traffic by default.','They allow all outbound traffic by default.', 2, -1);
insert into questions(ques_id, fk_uni_que_set, actual_question, optionA, optionB, optionC, optionD, answer, choose) values(10, 2, 'A company needs to run an application that is fault tolerant and tolerates interruptions on AWS. Which pricing model would best fit their requirements and help them lower costs as much as possible?', 'On-Demand Instances', 'Reserved Instances', 'Dedicated Instances', 'Dedicated Instances', 4, -1);
